controller_list:
  - name: ""
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: endeffector_controller
    action_ns: gripper_action
    type: GripperCommand
    default: true
    joints:
      - finger_joint


initial:
  - group: manipulator
    pose:  up
